---
title: "Cosine Models"
author: "Patrisha C. Miller"
date: "2024-07-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cosine Models

The following packages will be needed.

```{r packages, }
library(ggplot2);library(dplyr);library(readxl);library(tidyverse)
```

## Single File Version

The file links to my desktop, will change in the future.

```{r data frame organization}
# Read in file. From the shared folder, will have to change "User" (patri) to your own personal user

file <- "C:\\Users\\patri\\OneDrive - Chatham University\\Trish_Summer2024\\FernowTrish\\Compiled2\\Camp Hollow water.xlsx"

d <-read_excel(file)

# Change Column names so they're easy to work with
colnames(d) <- c('obs', 'date', 'temp')

# Remove random blank columns
d <- d[,-4] ; d <- d[,-4]

#Remove Other random NA
d <- na.omit(d)

#Setting a start date
startDate <- as.POSIXct("1900-01-01", tz = "UTC")

# New column that has the difference in days
d$dateNumeric <- as.numeric(difftime(d$date, startDate, units = "days"))

# Reference date to create a date decimal column
refDate <- as.POSIXct("2023-01-01", tz = "UTC")
ref <- as.numeric(difftime(refDate, startDate, units = 'days'))

d$decimalDate <- (d$dateNumeric - ref)/365

# Average temp
avTemp <- mean(d$temp, na.rm = T)

# New column with Mean Error
d$meanError <- (d$temp - avTemp)^2


```

The model

```{r the model}

#Use linear model function to estimate temperature based on the date-time yearly fraction using a fourier series
temp2 <- lm(temp ~ sin(2*pi*decimalDate) + cos(2*pi*decimalDate),data=d) 

#Create a vector of the estimated values
TempModel <- temp2$fitted.values

#Making the model a data frame to put onto one graph
e <- as.data.frame(TempModel)

#Adding this to OG data frame
d$model <- e$TempModel

# New column with model error
d$modelError <- (d$temp - d$model)^2

# Finding the mean of the model
Mean <- mean(d$model, na.rm= T)

# Finding the amplitude of the model
Amplitude <- max(d$model, na.rm = T) - Mean

# Finding the Phase

# Find the index of the first maximum value in the model column
max_index <- which.max(d$model)

# Get the Julian date corresponding to the first maximum value
datetime <- d$date[max_index]

Phase <- as.numeric(format(datetime, "%j")) + 
               (as.numeric(format(datetime, "%H")) * 3600 + 
                as.numeric(format(datetime, "%M")) * 60 + 
                as.numeric(format(datetime, "%S"))) / (24 * 3600)

#Getting logger name so that it can be the title of the graph
logger_name <- sub(" \\d{4}-\\d{2}-\\d{2}.*", "", basename(file))
logger_name <- sub("\\.xlsx$", "", logger_name)
```
## The Statistics

```{r stats}

RSSn <- sum(d$meanError)

RSSc <- sum(d$modelError)

Fstat <- ((RSSn - RSSc)/2)/(RSSc/(nrow(d)-3))

pval <- pf(Fstat, 2, (nrow(d)-3), lower.tail = F)

```
## The Graph

```{r graph}

# Define the x position for annotation outside the graph
x_position <- max(d$date) + 30 * 86400  # 30 days offset

# Plot with Annotations Outside the Graph
ggplot(d, aes(y = temp, x = date)) +
  geom_point() +
  geom_point(aes(y = model, x = date, color = 'red'), show.legend = FALSE) +
  labs(x = 'Date', y = 'Temperature (C°)', color = 'Model', title = logger_name) +
  scale_x_datetime(expand = expansion(mult = c(0, 0.3)), date_breaks = "3 months",date_labels = "%b %Y") +
  theme_classic() +
  theme(plot.margin = unit(c(1, 5, 1, 1), "lines")) +
  annotate("text", x = x_position, y = max(d$temp), label = paste("Mean:", round(Mean, 2)), size = 4, color = "black", hjust = 0) +
  annotate("text", x = x_position, y = max(d$temp) /1.16, label = paste("Amplitude:", round(Amplitude, 2)), size = 4, color = "black", hjust = 0)+
  annotate("text", x = x_position, y= max(d$temp) /1.40, label = paste("Phase:",round(Phase,2)), size = 4, color = 'black', hjust = 0)+
  annotate("text", x = x_position, y = max(d$temp) /4, label = paste("F = ",round(Fstat,2)),size = 4, color = 'black', hjust = 0)+
  annotate("text", x = x_position, y = max(d$temp) /8, label = paste("p << ", pval), size = 4, color = 'black', hjust = 0)

#ggsave(filename = paste0(logger_name, ".jpg"), dpi = 500, height = 100, width = 200, units = 'mm')

```

